alias .='cd .. && ls -Aph --color=auto'
alias ..='cd ../.. && ls -Aph --color=auto'
alias ...='cd ../../.. && ls -Aph --color=auto'
alias l='ls -Aph --color=auto'
alias r='rm -rf'
alias g='git clone'
alias gpl='git pull'
alias gp='git push'
alias gco='git checkout'
alias gcm='git checkout master'
alias gr='git remote -v'
alias gb='git branch -a'
alias gl='git log --pretty -n 2 --stat'
alias gs='git status -u'
alias ga='git add . && git add -A'
alias gf='git ls-files | grep'
alias gk='gitk --all --branches'
alias tree='tree -C'
alias dir='dir --color=auto'
alias ip='ip -c'
alias pcregrep='pcregrep --color=auto'
alias vdir='vdir --color=auto'
alias watch='watch --color'
alias cower='cower --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias py='python'
alias mk='mkdir'
alias gl='git log --pretty -n 2 --stat --decorate --all'
alias gc='git commit -m'
alias gi='git init'
alias pb='phpcs'
alias pbf='phpcbf'
alias hist='history'
alias n='nano'
alias less='less -SR'
alias x='exit'
alias yt='youtube-dl'
alias mp4='youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
alias mp3='youtube-dl -x --audio-format "mp3" --audio-quality 0 --embed-thumbnail $*'
alias mocp="mocp; mocp -x"
alias clear_cache="paccache -rk0"
alias gpfw="python ~/GitHub/gopro_fw_dl/gopro-fw-dl.py"
alias inotify_increase="echo fs.inotify.max_user_watches=524288 | tee /etc/sysctl.d/40-max-user-watches.conf && sysctl --system"
alias fixadb="adb kill-server && adb devices"
alias dmenu_fixed="dmenu_run -fn '-xos4-terminus-medium-r-*-*-14-*' -h 26"
alias cleanphoto="exiftool -all= $*"
alias mv='mv -v'
alias cp='cp -R'
alias docker_start='systemctl start docker'
alias docker_debian='docker run -it debian /bin/bash'
alias docker_psh='docker run -it microsoft/powershell'
alias pcregrep='pcregrep --color=auto'
alias watch='watch --color=auto'
alias cower='cower --color=auto'
alias msf='./me.sh'''
alias ip='curl ifconfig.me'
alias ifc='ifconfig wlan0'
alias pu='pkg update -y && pkg upgrade -y'
alias au='apt update -y && apt upgrade -y'
alias uu='au && pu'
alias ch='chmod +x'
alias py='python3'
alias python='python3'
alias p2='python2'
alias p3='python3'
alias python='python3'
alias webserver='python3 -m http.server 8080'
alias lazy='cd $HOME/Lazymux python3 lazymux.py'
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"
alias chcolor='/data/data/com.termux/files/home/.termux/colors.sh'
alias chfont='/data/data/com.termux/files/home/.termux/fonts.sh'
alias scr='cd /sdcard/scripts && ls -Aph --color=auto'
alias sd='cd /sdcard && ls -Aph --color=auto'
alias ve='virtualenv venv -p python3'
alias va='source venv/bin/activate'
alias gh='cd /sdcard/github && ls -Aph --color=auto'
alias ins='cd /sdcard/installs && ls -Aph --color=auto'
alias pyth='cd /sdcard/python && ls -Aph --color=auto' 
alias her='cd /sdcard/apps/heroku && ls -Aph --color=auto' 
alias app='cd /sdcard/apps1 && ls -Aph --color=auto' 
alias d='cd /sdcard/downloads && ls -Aph --color=auto' 
alias doc='cd /sdcard/docs && ls -Aph --color=auto'
alias sdcard='cd /storage/4932-72CF/ && ls -Aph --color=auto'
alias h='~ && ls -Aph --color=auto'
